#!/usr/bin/env bash

version=0.1.0

dir_name=intercity-server-${version}-linux-x86_64
file_name=${dir_name}.tar.gz
download_url=https://intercityup.com/downloads/linux_x86_64/${file_name}

bin_dir="/var/intercity-cli"
source_line="export PATH=\$PATH:${bin_dir}"

update_profile() {
  [ -f $1 ] || return 1

  cat $1 | grep "$source_line" > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "$source_line" >> $1
  fi
  export source_file=$1
}

update_profile $HOME/.zshrc || update_profile $HOME/.bashrc || update_profile $HOME/.bash_profile

echo "Downloading the Intercity CLI"
wget -q $download_url -O /tmp/${file_name}

echo "Installing Intercity CLI"
tar xf /tmp/${file_name} -C /tmp/

rm -rf /var/intercity-cli
mv /tmp/${dir_name} /var/intercity-cli

rm /tmp/${file_name}

echo "Starting to install Intercity"
/var/intercity-cli/intercity-server install

echo "Installed: Intercity CLI (Version ${version})"
echo
echo "Please restart your terminal session or to get started right away run:"
echo " source ${source_file}"
echo
echo "Run 'intercity-server' to see help"
echo
